spring.application.name=geoachados

spring.datasource.url=jdbc:postgresql://localhost:5432/gisdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect