spring.application.name=geoachados

spring.datasource.url=jdbc:postgresql://localhost:5432/gisdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

api.security.token.secret=${JWT_SECRET:q8kPEOgKrsyT47hn3AUzaSWo0U/YxvSyZCTkG38mr6k=}

# Configuracao do Minio

minio.bucket.name=geoachados
minio.access.key=AdminUser1
minio.acess.secret=S3nh@F0rte!
minio.url=http://localhost:9000


spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB