spring.application.name=geoachados

spring.datasource.url=jdbc:postgresql://localhost:5432/gisdb
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

api.security.token.secret=${JWT_SECRET:q8kPEOgKrsyT47hn3AUzaSWo0U/YxvSyZCTkG38mr6k=}

# =========================
# MINIO
# =========================

minio.bucket.name=geoachados
minio.access.key=AdminUser1
minio.access.secret=S3nh@F0rte!
minio.url=http://localhost:9000

# =========================
# MULTIPART
# =========================

spring.servlet.multipart.enabled=true

spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB

server.tomcat.max-http-form-post-size=200MB
server.tomcat.max-part-count=50